"use client";

import { AppData, Project } from "./types";
import { categoryId, defaultCapitalBuffer, defaultMasterCategories, defaultMenuMixItems, defaultReadinessScore, defaultRiskChecklist, defaultRiskItems, defaultSettings, defaultStaffPlan, seedData } from "./seed";

const KEY = "fnb-consult-data-v1";

export function loadData(): AppData {
  if (typeof window === "undefined") return seedData;
  const raw = localStorage.getItem(KEY);
  if (!raw) {
    localStorage.setItem(KEY, JSON.stringify(seedData));
    return seedData;
  }
  try {
    return migrateData(JSON.parse(raw) as AppData);
  } catch {
    localStorage.setItem(KEY, JSON.stringify(seedData));
    return seedData;
  }
}

export function saveData(data: AppData) {
  localStorage.setItem(KEY, JSON.stringify(data));
}

export function touchProject(project: Project): Project {
  return { ...project, updatedAt: new Date().toISOString() };
}

function migrateData(data: AppData): AppData {
  const oldCategories = data.settings?.categories;
  const oldChecklist = (data.settings?.defaultChecklistItems || []) as unknown[];
  const masterCategories = mergeMasterCategories([
    ...(data.settings?.masterCategories || []),
    ...defaultMasterCategories,
    ...stringCategoriesToMaster(oldCategories?.setup || [], "setup_budget"),
    ...stringCategoriesToMaster(oldCategories?.product || [], "product"),
    ...stringCategoriesToMaster(oldCategories?.equipment || [], "equipment"),
    ...stringCategoriesToMaster(oldCategories?.expense || [], "expense"),
    ...stringCategoriesToMaster(oldCategories?.staff || [], "staff"),
  ]);
  const settings = {
    ...defaultSettings,
    ...(data.settings || {}),
    masterCategories,
    defaultChecklistItems: migrateChecklistLibrary(oldChecklist, masterCategories),
    categories: {
      ...defaultSettings.categories,
      ...(data.settings?.categories || {}),
      setup: unique([...(defaultSettings.categories.setup || []), ...((data.settings?.categories?.setup || []) as string[])]),
      product: unique([...(defaultSettings.categories.product || []), ...((data.settings?.categories?.product || []) as string[])]),
      expense: unique([...(defaultSettings.categories.expense || []), ...((data.settings?.categories?.expense || []) as string[])]),
      equipment: unique([...(defaultSettings.categories.equipment || []), ...((data.settings?.categories?.equipment || []) as string[])]),
      staff: unique([...(defaultSettings.categories.staff || []), ...((data.settings?.categories?.staff || []) as string[])]),
    },
  };
  const projects = (data.projects || []).map((project) => ({
    ...project,
    continuationType: project.continuationType || "brand_new_project",
    setupBudget: (project.setupBudget || []).map((item) => migrateSetupItem(item, masterCategories)),
    staffPlan: project.staffPlan || defaultStaffPlan(),
    monthlyProjection: {
      ...project.monthlyProjection,
      costs: project.monthlyProjection?.costs || {},
      useManualStaffSalary: project.monthlyProjection?.useManualStaffSalary || false,
      manualStaffSalary: project.monthlyProjection?.manualStaffSalary || project.monthlyProjection?.costs?.["Staff salary"] || 0,
    },
    riskItems: (project.riskItems || defaultRiskItems()).map(migrateRiskItem),
    menuMix: migrateMenuMix(project.menuMix),
    menuMixPlan: project.menuMixPlan || { id: cryptoId(), items: defaultMenuMixItems(), notes: project.menuMix?.notes || "", updatedAt: new Date().toISOString() },
    capitalBuffer: project.capitalBuffer || { ...defaultCapitalBuffer(), bufferPercentage: project.openingBuffer?.percentage || 10 },
    riskChecklist: project.riskChecklist ? { ...project.riskChecklist, items: project.riskChecklist.items.map(migrateRiskItem) } : { ...defaultRiskChecklist(), items: (project.riskItems || defaultRiskItems()).map(migrateRiskItem) },
    readinessScore: project.readinessScore || defaultReadinessScore(),
    openingBuffer: project.openingBuffer || { percentage: 10 },
  }));
  return { projects, settings };
}

function unique(values: string[]) {
  return Array.from(new Set(values.filter(Boolean)));
}

function migrateRiskItem(item: any) {
  return {
    id: item.id || cryptoId(),
    title: item.title || "Risk item",
    level: item.level || "Medium",
    active: item.active ?? item.checked ?? false,
    notes: item.notes || "",
    recommendation: item.recommendation || "",
    responsiblePerson: item.responsiblePerson || "",
    targetResolutionDate: item.targetResolutionDate || "",
    status: item.status || "Open",
    autoGenerated: item.autoGenerated || false,
    checked: item.checked || false,
  };
}

function migrateMenuMix(menuMix: Project["menuMix"] | undefined) {
  return {
    beverageCount: menuMix?.beverageCount ?? 0,
    foodCount: menuMix?.foodCount ?? 0,
    dessertSnackCount: menuMix?.dessertSnackCount ?? 0,
    ownProductPercentage: menuMix?.ownProductPercentage ?? 70,
    vendorConsignmentPercentage: menuMix?.vendorConsignmentPercentage ?? 30,
    heroProductTarget: menuMix?.heroProductTarget ?? "",
    highMarginProducts: menuMix?.highMarginProducts ?? "",
    lowMarginProducts: menuMix?.lowMarginProducts ?? "",
    notes: menuMix?.notes ?? "",
  };
}

function stringCategoriesToMaster(values: string[], type: "setup_budget" | "product" | "equipment" | "expense" | "staff") {
  const now = new Date().toISOString();
  return values.filter(Boolean).map((name) => ({ id: categoryId(type, name), name, type, active: true, createdAt: now, updatedAt: now }));
}

function mergeMasterCategories(values: AppData["settings"]["masterCategories"]) {
  const map = new Map<string, AppData["settings"]["masterCategories"][number]>();
  values.forEach((category) => {
    const key = `${category.type}:${category.name}`.toLowerCase();
    map.set(key, { ...category, id: category.id || categoryId(category.type, category.name), active: category.active !== false, createdAt: category.createdAt || new Date().toISOString(), updatedAt: category.updatedAt || new Date().toISOString() });
  });
  return Array.from(map.values());
}

function findCategoryIdByName(name: string, masterCategories: AppData["settings"]["masterCategories"], type: "setup_budget") {
  return masterCategories.find((category) => category.type === type && category.name === name)?.id || masterCategories.find((category) => category.type === type && category.name === "Other")?.id || categoryId(type, name || "Other");
}

function migrateChecklistLibrary(items: unknown[], masterCategories: AppData["settings"]["masterCategories"]) {
  const now = new Date().toISOString();
  if (!items.length) return defaultSettings.defaultChecklistItems;
  return items.map((raw) => {
    const item = raw as Record<string, unknown>;
    const categoryName = String(item.category || "Other");
    return {
      id: String(item.id || cryptoId()),
      name: String(item.name || "Checklist item"),
      categoryId: String(item.categoryId || findCategoryIdByName(categoryName, masterCategories, "setup_budget")),
      defaultEstimatedPrice: Number(item.defaultEstimatedPrice || 0),
      defaultQuantity: Number(item.defaultQuantity || 1),
      required: item.required !== false,
      active: item.active !== false,
      notes: String(item.notes || ""),
      createdAt: String(item.createdAt || now),
      updatedAt: String(item.updatedAt || now),
    };
  });
}

function migrateSetupItem(item: Project["setupBudget"][number], masterCategories: AppData["settings"]["masterCategories"]) {
  const now = new Date().toISOString();
  return {
    ...item,
    categoryId: item.categoryId || findCategoryIdByName(item.category, masterCategories, "setup_budget"),
    itemSource: item.itemSource || "new_item_to_buy",
    originalPurchasePrice: item.originalPurchasePrice ?? item.actualPrice ?? 0,
    currentEstimatedValue: item.currentEstimatedValue ?? item.actualPrice ?? 0,
    paidByPartnerId: item.paidByPartnerId || "",
    assetOwnerPartnerId: item.assetOwnerPartnerId || item.paidByPartnerId || "",
    condition: item.condition || "Good",
    stillUsableForNewConcept: item.stillUsableForNewConcept ?? true,
    countAsCapitalContribution: item.countAsCapitalContribution ?? false,
    sourceLibraryItemId: item.sourceLibraryItemId || "",
    createdAt: item.createdAt || now,
    updatedAt: item.updatedAt || now,
  };
}

function cryptoId() {
  const randomUUID = globalThis.crypto?.randomUUID;
  if (randomUUID) return randomUUID.call(globalThis.crypto);
  return `id-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
}
